# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Viraj Jain
# For architectural decisions and proof of correctness, please refer to:
# - docs/THESIS.tex
# - docs/PROOF_DOSSIER.md
"""Temporal constraint primitives using UNIX epoch integer fields.

Design note: Time fields must be declared as ``Int``-sorted in the Policy,
representing UNIX timestamps (seconds since epoch).  This avoids floating-
point imprecision and makes Z3 arithmetic exact.

.. warning:: **TRUSTED STATE REQUIREMENT**

    All bound fields in these primitives (``now_ts``, ``window_start``,
    ``window_end``, ``cutoff``) are populated from the values dict passed to
    ``Guard.verify()``.  If the caller controls the ``state`` dict, they can
    bypass temporal enforcement entirely by setting:

    * ``now_ts=0``                  → every token/cert appears permanently valid
    * ``window_start=0, window_end=9999999999`` → any time passes the window

    **Fix**: populate time fields exclusively via ``trusted_state`` (the
    third parameter to ``Guard.verify()``), never from caller-supplied
    ``intent`` or ``state``.  Example::

        import time
        decision = guard.verify(
            intent=user_intent,
            state=caller_state,
            trusted_state={
                "now_ts": int(time.time()),
                "window_start": schedule.start_unix,
                "window_end": schedule.end_unix,
            },
        )

    Fields in ``trusted_state`` override matching keys in ``state``, so a
    caller cannot inject their own ``now_ts`` even if they try.

Example::

    import time
    from pramanix.primitives.time import NotExpired, WithinTimeWindow

    class TokenPolicy(Policy):
        expiry_ts = Field("expiry_ts", int, "Int")
        now_ts    = Field("now_ts",    int, "Int")

        @classmethod
        def invariants(cls):
            return [NotExpired(cls.expiry_ts, cls.now_ts)]
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pramanix.expressions import E

if TYPE_CHECKING:
    from pramanix.expressions import ConstraintExpr, Field

__all__ = [
    "After",
    "Before",
    "NotExpired",
    "WithinTimeWindow",
]


def WithinTimeWindow(
    timestamp: Field,
    window_start: Field,
    window_end: Field,
) -> ConstraintExpr:
    """Enforce that a timestamp falls inside [window_start, window_end].

    DSL: ``(E(timestamp) >= E(window_start)) & (E(timestamp) <= E(window_end))``

    Args:
        timestamp:    Field representing the event/request timestamp.
        window_start: Field representing the window open time (UNIX epoch, Int).
        window_end:   Field representing the window close time (UNIX epoch, Int).
    """
    return (
        ((E(timestamp) >= E(window_start)) & (E(timestamp) <= E(window_end)))
        .named("within_time_window")
        .explain(
            "Request outside allowed time window: timestamp ({timestamp}) "
            "is not in [{window_start}, {window_end}]."
        )
    )


def After(timestamp: Field, cutoff: Field) -> ConstraintExpr:
    """Enforce that a timestamp is strictly after the cutoff.

    DSL: ``(E(timestamp) > E(cutoff))``

    Args:
        timestamp: Field representing the event timestamp.
        cutoff:    Field representing the earliest acceptable timestamp.
    """
    return (
        (E(timestamp) > E(cutoff))
        .named("after_cutoff")
        .explain("Too early: timestamp ({timestamp}) is not after cutoff ({cutoff}).")
    )


def Before(timestamp: Field, cutoff: Field) -> ConstraintExpr:
    """Enforce that a timestamp is strictly before the cutoff.

    DSL: ``(E(timestamp) < E(cutoff))``

    Args:
        timestamp: Field representing the event timestamp.
        cutoff:    Field representing the latest acceptable timestamp.
    """
    return (
        (E(timestamp) < E(cutoff))
        .named("before_cutoff")
        .explain("Too late: timestamp ({timestamp}) is not before cutoff ({cutoff}).")
    )


def NotExpired(expiry_ts: Field, now_ts: Field) -> ConstraintExpr:
    """Enforce that the entity has not yet expired.

    DSL: ``(E(expiry_ts) > E(now_ts))``

    Args:
        expiry_ts: Field representing the expiry timestamp of the entity
                   (certificate, token, session, …).
        now_ts:    Field representing the current time (UNIX epoch, Int).
                   Must be provided by the caller — never generated by the guard.
    """
    return (
        (E(expiry_ts) > E(now_ts))
        .named("not_expired")
        .explain("Entity has expired: expiry_ts ({expiry_ts}) <= now_ts ({now_ts}).")
    )
